
source 'https://github.com/IUCoco/FMPrivateSpec.git'
source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!

target 'XMGFMMain_Example' do
  pod 'XMGFMMain', :path => '../'

  target 'XMGFMMain_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
